spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,log4j
      web-stat-filter.enabled: true
  #redis配置
  redis:
    host: 101.37.86.173
    port: 6379
    database: 1
    password: 
    timeout: 10000
# 日志设置
logging:
  level:
    root: info
    com.dsy.blog: debug
  file:
    name: log/bolg-dev.log
